### ISSUE TITLE
Work with @ scoped / npm private modules?

### ISSUE THREAD

**Issue by homerjam** [dylang/npm-check#45]
Hi,

Thanks, this is a super useful tool.

Could it be made to work with private npm modules, ie. those scoped by username like `@username/packagename`?

James

**Comment by dylang** [comment]
Thanks James - it should be working with scoped modules. I don't have access to any private modules to try, I'll see what I can do.

**Comment by homerjam** [comment]
Great thanks, I think I can give you access to one of mine if it would help.

**Comment by dylang** [comment]
Sure, thanks!

**Comment by homerjam** [comment]
I've made a dummy module which is private and added you as a collaborator - its called `@homerjam/dummy-module`. Let me know if I can do anything else to help.

**Comment by sindresorhus** [comment]
Scoped modules doesn't have to be private. Example: https://www.npmjs.com/package/%40sindresorhus%2Fdf

I just fixed support for scoped packages in [`package-json`](https://github.com/sindresorhus/package-json). Just upgrade to 2.0.0 and it should just work. (Note that the interface changed from callback-style to promise).

**Comment by dylang** [comment]
Nice, thanks @sindresorhus, and I appreciate that you've changed it to promises.

**Comment by dylang** [comment]
Ha, @sindresorhus, my brain had a bug. While I do appreciate the change to promises, what I *really* meant to write is that I appreciate that you shared the update news here in this ticket so I can easily address the problem! Thanks for saving me time trying to figure out what's wrong and helping the `npm-check` users. :heart_eyes: 

New version soon to fix this.

**Comment by homerjam** [comment]
Hmm, not sure if I'm doing something wrong here but this still isn't working for me. I've updated to 4.1.0 but still seeing `Registry error Package or version doesn't exist`.

@dylang is `@homerjam/dummy-module` working for you?

**Comment by dylang** [comment]
Thanks for this feedback @homerjam. I'll reopen and investigate the problem.

**Comment by dylang** [comment]
@homerjam, i'm not finding `@homerjam/dummy-module` in the npm registry.

Example of a scoped module found:
https://www.npmjs.com/package/@websdk/nap

Not found:
https://www.npmjs.com/package/@homerjam/dummy-module

**Comment by homerjam** [comment]
@dylang did you login?

Here's the page that about the type of modules I'm talking about (in case there's some confusion).

https://www.npmjs.com/private-modules

**Comment by dylang** [comment]
Oops, good catch @homerjam! I didn't notice that `npmjs.com` logged me out. 

Once logged in I didn't realize I had to also pay the $7/month to access private modules. I'll do that too, very happy to support Isaac and team.

**Comment by homerjam** [comment]
Ah, it never occurred to me that collaborators would also need to pay! $7 is very reasonable I think but I had intended to allow access to some of my modules to other users without them needing to pay necessarily.

**Comment by dylang** [comment]
I forgot too, because it's not how it works on Github.com. 

I've paid for my account, and I'm able to repro the issue. It appears that `package-json` does not support private packages because it doesn't send the auth token. I'll create an issue for that project.

**Comment by dylang** [comment]
https://github.com/sindresorhus/package-json/issues/12 created.

**Comment by homerjam** [comment]
I've found an annoying problem that I've created a temporary solution to [here](https://github.com/sindresorhus/package-json/pull/14). Be great to get your thoughts and eventually bring this in to npm-check.

**Comment by homerjam** [comment]
Hi @dylang package-json has now been updated to fix the above. Would you mind updating the dependencies when you get a chance? Thanks!

**Comment by dylang** [comment]
Hi @homerjam, thanks for following this and letting me know there's now a fix.

Just re-install `npm-check` to get the updated `package-json`. 

```
npm i -g i npm-check
```

**Comment by homerjam** [comment]
Oh I see! Great, thanks
